language: node_js
node_js:
    - "6.2"
    - "6.1"
    - "6"
    - "5.1"
    - "4"
    - "4.2"
    - "4.1"
    - "4.0"

before_script:
    - npm install
    - phpenv global 5.6 2>/dev/null
    - phpenv global 5.6
    - curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/bin --filename=composer

script: npm test
